[default]
address = "127.0.0.1"
port = 8000
# workers = 16
# max_blocking = 512
# keep_alive = 5
# ident = "Rocket"
# ip_header = "X-Real-IP" # set to `false` to disable
log_level = "normal"
temp_dir = "/tmp"
cli_colors = true
secret_key = "enk5I14sTWBePWFaNFZQLXpNOmAmS2B8Ull6S2xlM1pt"